# Welcome to Jekyll!
# Documentation: https://jekyllrb.com/docs/configuration/
#      defaults: https://jekyllrb.com/docs/configuration/#default-configuration
#
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Read more about defaults: https://github.com/envygeeks/jekyll-assets/blob/master/README.md
title: Sato Sailing Club
description: Sailing for fun and learning
#email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://satosailing.club" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: false
show_projectpage: false

google_analytics: UA-107316710-1
permalink: /:categories/:title/

#collections:

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: Michael Stewart
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: post
#   - scope:
#       path: "blocks"
#       type: blocks
#     values:
#      published: false


## SITE NAVIGATION
# By default, all pages in your site are added to navigation.
# If you want to link only specific pages or posts in your header, uncomment
# this and add the path to the pages in order as they should show up
# Note: Any values are overridden by _data/header_pages.yml
#header_pages:
# - about.md


# Build settings
# ██████  ██    ██ ██ ██      ██████      ███████ ███████ ████████ ████████ ██ ███    ██  ██████  ███████
# ██   ██ ██    ██ ██ ██      ██   ██     ██      ██         ██       ██    ██ ████   ██ ██       ██
# ██████  ██    ██ ██ ██      ██   ██     ███████ █████      ██       ██    ██ ██ ██  ██ ██   ███ ███████
# ██   ██ ██    ██ ██ ██      ██   ██          ██ ██         ██       ██    ██ ██  ██ ██ ██    ██      ██
# ██████   ██████  ██ ███████ ██████      ███████ ███████    ██       ██    ██ ██   ████  ██████  ███████

# Github-pages list of gems https://pages.github.com/versions/
plugins:
  - jekyll-feed             # SEO generate an Atom (RSS-like) feed of your Jekyll posts — https://github.com/jekyll/jekyll-feed
  - jekyll-redirect-from    # SEO 301 redirects — https://github.com/jekyll/jekyll-redirect-from
  - jekyll-seo-tag          # SEO add metadata tags for search & social networks — https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap          # SEO Generate a sitemaps.org compliant sitemap — https://github.com/jekyll/jekyll-sitemap
#  - jekyll-paginate         # Jekyll Built-in Pagination Generator for Jekyll
#  - jekyll-readme-index     # Jekyll Render a project's README as the site's index — https://github.com/benbalter/jekyll-readme-index/
#  - jekyll-avatar           # Liquid  rendering GitHub avatars — https://github.com/benbalter/jekyll-avatar/
#  - jekyll-gist             # Liquid Liquid tag for displaying GitHub Gists — https://github.com/jekyll/jekyll-gist/
#  - jekyll-mentions         # GFM @mention support for your Jekyll site — https://github.com/jekyll/jekyll-mentions
#  - jekyll-relative-links   # GFM convert relative links to markdown files to their rendered equivalents — https://github.com/benbalter/jekyll-relative-links/
  - jemoji                  # GFM GitHub-flavored Emoji plugin for Jekyll — https://github.com/jekyll/jemoji
#  - jekyll-titles-from-headings # Generate page title from the first Markdown heading when none is specified — https://github.com/benbalter/jekyll-titles-from-headings
#
# Won't work on github pages, and will need to be added to Gemfile
#  - jekyll-admin            # Provides a traditional CMS-style graphical interface to author and administer Jekyll — Docs: https://github.com/jekyll/jekyll-admin
#  - jekyll-bootstrap-sass   # Docs: http://www.rubydoc.info/gems/jekyll-bootstrap-sass/0.1.0
#  - bootstrap-sass          # Docs: http://www.rubydoc.info/gems/bootstrap-sass
#
# Jekyll Github-pages requires the following Gems by default.
# Therefore, read the docs if you want to change default configurations.
#      - jekyll-coffeescript              # https://github.com/jekyll/jekyll-coffeescript
#      - jekyll-default-layout            # https://github.com/benbalter/jekyll-default-layout
#      - jekyll-gist                      # https://github.com/jekyll/jekyll-gist
#      - jekyll-github-metadata           # https://github.com/jekyll/github-metadata
#      - jekyll-optional-front-matter     # https://github.com/benbalter/jekyll-optional-front-matter
#      - jekyll-paginate                  # https://github.com/jekyll/jekyll-paginate
#      - jekyll-readme-index              # https://github.com/benbalter/jekyll-readme-index
#      - jekyll-relative-links            # https://github.com/benbalter/jekyll-relative-links
#      - jekyll-titles-from-headings      # https://github.com/benbalter/jekyll-titles-from-headings

liquid:
  error_mode: strict #warn  #lax
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Github Metadata (github-pages)
# Docs https://github.com/jekyll/github-metadata
repository: mdrmike/satosailing                                   # username/repo-name

# Jekyll Sass Converter: https://github.com/jekyll/jekyll-sass-converter/
# Docs: https://jekyllrb.com/docs/assets/#sassscss
sass:
    sass_dir: assets/_sass
    style: compressed #nested expanded compact compressed

# JEKYLL-REDIRECT-FROM
# If you're using Jekyll in safe mode to mimic GitHub Pages, make sure to add
# jekyll-redirect-from to your whitelist:
#whitelist:
#  - jekyll-redirect-from


# JEKYLL-SEO-TAG
# ███████ ███████  ██████
# ██      ██      ██    ██
# ███████ █████   ██    ██
#      ██ ██      ██    ██
# ███████ ███████  ██████
# Usage: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# Advanced usage: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md

logo: /assets/images/logo.png
name: config_yml__name  # default author for posts. (defaults to site.title if null)

# default author for posts. (defaults to site.title if null)
#author:
#  twitter: config_yml__author_twitter

#twitter:
#  username: config_yml__twitter_username

facebook:
  app_id: config_yml__facebook_app_id
  publisher: config_yml__facebook_publisher
  admins: config_yml__facebook_admins

social:
  links: [ "https://twitter.com/config_yml__social", "https://www.facebook.com/config_yml__social", "https://www.linkedin.com/in/config_yml__social", "https://plus.google.com/+config_yml__social", "https://keybase.io/config_yml__social", "https://github.com/config_yml__social"]
  name: config_yml__social_name

webmaster_verifications:
  google: config_yml__webmaster_google
  bing: config_yml__webmaster_bing
  alexa: config_yml__webmaster_alexa
  yandex: config_yml__webmaster_yandex

disqus:
  shortname: satosailing # Your disqus shortname, entering this will enable commenting on posts

lang: en_US
